# Generated by Django 2.0.3 on 2018-03-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uuid', models.IntegerField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('finger_print', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint_device',
            fields=[
                ('location', models.CharField(max_length=100)),
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LED_bulb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mappingstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_station_name', models.CharField(max_length=20)),
                ('ghatkopar', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=20)),
                ('fare', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('source', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='biometric_ticket.Mappingstation')),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometric_ticket.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometric_ticket.Customer')),
            ],
        ),
    ]
