# Generated by Django 2.0.3 on 2018-04-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_ticket', '0002_auto_20180330_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint_device',
            name='finger_print_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='money',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='uuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biometric_ticket.Customer'),
        ),
    ]
