# Generated by Django 2.0.3 on 2018-04-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_ticket', '0004_auto_20180410_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
