# Generated by Django 2.0.3 on 2018-04-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_ticket', '0005_auto_20180410_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
